---
title: "Corbett_DataAnalysis_103122"
output: 
  html_document:
    toc: true
    toc_float: true
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
library(dplyr) #data wrangling
library(haven) #data import
library(tidyverse) # data wrangling
library(summarytools)
library(psych) # psych analysis
library(readxl) # read xlsx 
library(lavaan) #sem
```

# import dataset
```{r}
data_original <- read_excel("Rawdata_Corbett1.xlsx")
data_original
```

# Youjin: descriptive statistics
```{r descriptives, echo=FALSE}
#check for missing values
summary(data_original)

#calculate the number of missing values per participant
table(rowSums(is.na(data_original))) #max of 6 missing values per participant

data_original %>%
  filter(rowSums(is.na(data_original))>0) %>%
  view() 
##44 participants have at least two missing values
#(1) 4 students do not have any intervention data (will be removed)
#(2) From (1), 4 students additionally do not have pre-test data (remove?)
#(3) From (1), 22 students additionally do not have post-test data (but 6 of them have follow-up data)

    ##investigate missing data
    missing <- data_original %>%
      filter(rowSums(is.na(data_original))>0)
    
    summary(missing)
    freq(missing$group) # more people in control have missing data
    freq(missing$sex) # more males have missing data
    
#####missing data between treatment and control groups
    
#demographics
summary(data_original) 
##mean age: 12.6
##mean severity: 7.4 (3-10 range)
##mean IQ: 98 (60-140 range)
##outliers in dependent variables
freq(data_original$group) #55% in treatment, 45% in control
freq(data_original$sex) #71% male, 29% female

hist(data_original$face_rep_pre)
hist(data_original$face_rep_post)
hist(data_original$face_sng_pre)
hist(data_original$face_sng_post)
```

# Zoe: Missing Data
1. remove 4 participants with no clinical data

```{r}
#summary of missing data
data_original[!complete.cases(data_original),]

#remove participants w/o clinical data
data_01 <- data_original[-c(53, 55, 56, 198),] 
```

2. run regressions with casewise deletion (data_02)

```{r}
dim(data_01)[1]
data_02 <- na.omit(data_01) 
dim(data_02)[1]
```

3. run regressions with FIML

```{r}
colnames(data_02)
```

### Becky: Regression w/ Sex


describeBy(data_02, data_02$sex, mat = TRUE)
```{r}
# Casewise Deletion
# Linear regression: single face w/ sex
sng.sex <- lm(face_sng_post ~ face_sng_pre+group+sex+group:sex, data = data_02)
summary(sng.sex)

```
```{r}
# Linear regression: repeated face w/ sex
rep.sex <- lm(face_rep_post ~ face_rep_pre+group+sex+group:sex, data = data_02)
summary(rep.sex)
```

```{r}
#FIML-Single face
#create regression model object
model <- 'face_sng_post ~ face_sng_pre+group+sex+group:sex'

# fit the model
fit.sex <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.sex, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```

```{r}
#FIML-repeated face
#create regression model object
model <- 'face_rep_post ~ face_rep_pre+group+sex+group:sex'

# fit the model
fit.sex <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.sex, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```

### Raunak: Regression w Severity

```{r}
# Linear regression: single face w/ severity
sng.sev <- lm(face_sng_post ~ face_sng_pre+group+scoresumm_compscore+group:scoresumm_compscore, data = data_02)
summary(sng.sev)
```

```{r}
# Linear regression: repeated face w/ severity
rep.sev <- lm(face_rep_post ~ face_rep_pre+group+scoresumm_compscore+group:scoresumm_compscore, data = data_02)
summary(rep.sev)
```

```{r}
#create regression model object
model <- 'face_sng_post ~ face_sng_pre+group+scoresumm_compscore+group:scoresumm_compscore'

# fit the model
fit.sev <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.sev, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```

```{r}
#create regression model object
model <- 'face_rep_post ~ face_rep_pre+group+scoresumm_compscore+group:scoresumm_compscore'

# fit the model
fit.sev <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.sev, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```


### Regression w IQ

```{r}
# Linear regression: single face w/ IQ
sng.iq <- lm(face_sng_post ~ face_sng_pre+group+full_scale_iq+group:full_scale_iq, data = data_02)
summary(sng.iq)
```

```{r}
# Linear regression: repeated face w/ IQ
rep.iq <- lm(face_rep_post ~ face_rep_pre+group+full_scale_iq+group:full_scale_iq, data = data_02)
summary(rep.iq)
```

```{r}
#create regression model object
model <- 'face_sng_post ~ face_sng_pre+group+full_scale_iq+group:full_scale_iq'

# fit the model
fit.iq <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.iq, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```

```{r}
#create regression model object
model <- 'face_rep_post ~ face_rep_pre+group+full_scale_iq+group:full_scale_iq'

# fit the model
fit.iq <- sem(model, data_01, missing = 'fiml', meanstructure = TRUE, fixed.x = FALSE)

# generate output
summary(fit.iq, fit.measures = TRUE, rsquare = TRUE, standardize = TRUE)
```


## Raunak: Visualizations

Sex

```{r}
 plot(data_02$sex, data_02$face_sng_post - data_02$face_sng_pre, xlab = "Sex", ylab = "Post-Pre difference scores")
```


Severity

```{r}
plot(data_02$scoresumm_compscore, data_02$face_sng_post - data_02$face_sng_pre, xlab = "Symptom severity", ylab = "Post-Pre difference scores")
```

IQ

```{r}
plot(data_02$full_scale_iq, data_02$face_sng_post - data_02$face_sng_pre, xlab = "IQ", ylab = "Post-Pre difference scores")
```


