---
title: "8880_ClassExercises"
output: html_document
date: "2023-02-08"
---
# Exercise 7
1. Transform a wide form of item responses below to a long (vector) form of item responses
```{r}
df <- matrix(0, 5, 3)

rownames(df) <- c("Person 1", "Person 2", "Person 3", "Person 4", "Person 5")
colnames(df) <- c("Item1", "Item2", "Item3")

df[1,] <- c(1, 0, 1)
df[2,] <- c(0, 0, 1)
df[3,] <- c(1, 0, 0)
df[4,] <- c(1, 1, 1)
df[5,] <- c(0, 1, 1)

df
```
```{r}
df_long <- matrix(0, 15, 3)

colnames(df_long) <- c("Person j", "Item i", "Item Response yji")
df_long
```
```{r}
df_long[1:3, 1] <- 1
df_long[4:6, 1] <- 2
df_long[7:9, 1] <- 3
df_long[10:12, 1] <- 4
df_long[13:15, 1] <- 5

df_long
```
```{r}
df_long[1:3, 2] <- c(1,2,3)
df_long[4:6, 2] <- c(1,2,3)
df_long[7:9, 2] <- c(1,2,3)
df_long[10:12, 2] <- c(1,2,3)
df_long[13:15, 2] <- c(1,2,3)

df_long
```
```{r}
df_long[1:3, 3] <- c(1,0,1)
df_long[4:6, 3] <- c(0,0,1)
df_long[7:9, 3] <- c(1,0,0)
df_long[10:12, 3] <- c(1,1,1)
df_long[13:15, 3] <- c(0,1,1)

df_long
```

